### ISSUE TITLE
Include Link to Unicode Table

### ISSUE THREAD

**Issue by jag3773** [Door43/translationKeyboardWeb#11]
We need to include a link to http://unicode-table.com/ somewhere on the site, maybe in several places so that people see that that is where they can copy and paste characters from.

**Comment by bknatterud** [comment]
when editing key there is a button that says search characters. We could put that same button in the main nav, ok?

**Comment by bknatterud** [comment]
Put a link in the navigation bar. Will push to site in a little bit.
