### ISSUE TITLE
Keyboard Name Should be Editable

### ISSUE THREAD

**Issue by jag3773** [Door43/translationKeyboardWeb#13]
The name of the keyboard should be editable.

**Comment by bknatterud** [comment]
You can actually do this by clicking on the Keyboard Name. See on this page...
http://tk.unfoldingword.org/language/bfj
Click on Bafanji after the words "Keyboard Name"
I could put this other places too. Let me know where you want it.

**Comment by jag3773** [comment]
Great, could you put a pencil icon net to that, so that it looks editable?

**Comment by bknatterud** [comment]
Done.
